### ISSUE TITLE
After the update, lambda eks-quickstart-RegisterType got the error

### ISSUE THREAD

**Issue by ruiyaoOps** [aws-quickstart/quickstart-qingcloud-kubesphere#78]
Hello @troy-ameigh 
After we updated, I got the following error when using the template to install EKS,
```shell
[ERROR] DistributionNotFound: The 'semantic_version' distribution was not found and is required by the application
Traceback (most recent call last):  File "/var/lang/lib/python3.7/imp.py", line 234, in load_module    return load_source(name, filename, file)  File "/var/lang/lib/python3.7/imp.py", line 171, in load_source    module = _load(spec)  File "<frozen importlib._bootstrap>", line 696, in _load  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked  File "<frozen importlib._bootstrap_external>", line 728, in exec_module  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed  File "/var/task/lambda_function.py", line 6, in <module>    from semantic_version import Version  File "/var/task/semantic_version/__init__.py", line 18, in <module>    __version__ = pkg_resources.get_distribution("semantic_version").version  File "/var/lang/lib/python3.7/site-packages/pkg_resources/__init__.py", line 482, in get_distribution    dist = get_provider(dist)  File "/var/lang/lib/python3.7/site-packages/pkg_resources/__init__.py", line 358, in get_provider    return working_set.find(moduleOrReq) or require(str(moduleOrReq))[0]  File "/var/lang/lib/python3.7/site-packages/pkg_resources/__init__.py", line 901, in require    needed = self.resolve(parse_requirements(requirements))  File "/var/lang/lib/python3.7/site-packages/pkg_resources/__init__.py", line 787, in resolve    raise DistributionNotFound(req, requirers) | [ERROR] DistributionNotFound: The 'semantic_version' distribution was not found and is required by the application Traceback (most recent call last):   File "/var/lang/lib/python3.7/imp.py", line 234, in load_module     return load_source(name, filename, file)   File "/var/lang/lib/python3.7/imp.py", line 171, in load_source     module = _load(spec)   File "<frozen importlib._bootstrap>", line 696, in _load   File "<frozen importlib._bootstrap>", line 677, in _load_unlocked   File "<frozen importlib._bootstrap_external>", line 728, in exec_module   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed   File "/var/task/lambda_function.py", line 6, in <module>     from semantic_version import Version   File "/var/task/semantic_version/__init__.py", line 18, in <module>     __version__ = pkg_resources.get_distribution("semantic_version").version   File "/var/lang/lib/python3.7/site-packages/pkg_resources/__init__.py", line 482, in get_distribution     dist = get_provider(dist)   File "/var/lang/lib/python3.7/site-packages/pkg_resources/__init__.py", line 358, in get_provider     return working_set.find(moduleOrReq) or require(str(moduleOrReq))[0]   File "/var/lang/lib/python3.7/site-packages/pkg_resources/__init__.py", line 901, in require     needed = self.resolve(parse_requirements(requirements))   File "/var/lang/lib/python3.7/site-packages/pkg_resources/__init__.py", line 787, in resolve     raise DistributionNotFound(req, requirers)
```
![image](https://user-images.githubusercontent.com/35256376/156958131-29593490-cd16-412b-8a2d-3416c57b00da.png)
I think it's caused by the lambda update. Should I change anything in the template?
We will keep on looking into this and hope you can provide some help.

**Comment by ruiyaoOps** [comment]
It has been confirmed that the problem is caused by [amazon-eks-per-region-resources.template.yaml](https://github.com/aws-quickstart/quickstart-amazon-eks/blob/main/templates/amazon-eks-per-region-resources.template.yaml), 
I will create an issue in [quickstart-amazon-eks](https://github.com/aws-quickstart/quickstart-amazon-eks/issues) after more testing

**Comment by ruiyaoOps** [comment]
@troy-ameigh I have created the issuse [Failed to create RegisterType resources](https://github.com/aws-quickstart/quickstart-amazon-eks/issues/397) in [quickstart-amazon-eks](https://github.com/aws-quickstart/quickstart-amazon-eks/issues)

**Comment by FeynmanZhou** [comment]
Hi @troy-ameigh ,

Could you please help to take a look at this issue? It has been blocking us and our users for so long. 

Thanks
Feynman

**Comment by FeynmanZhou** [comment]
> Hi @troy-ameigh ,
> 
> Could you please help to take a look at this issue? It has been blocking us and our users for so long.
> 
> Thanks Feynman

Just noticed this issue has been fixed in another [thread](https://github.com/aws-quickstart/quickstart-amazon-eks/issues/397#issuecomment-1076851512). We are verifying it.

**Comment by ruiyaoOps** [comment]
@troy-ameigh we still get failed to build, should we update the submodule and the files in s3?

**Comment by troy-ameigh** [comment]
@FeynmanZhou I am looking at this now
